var carries = [
  {
    name:"Rebozo",
    location:"front",
    baseModifier:-4,
    difficulty:"beginner",
    url:"http://www.babywearinghamptonroads.org/2014/01/carry-of-month-rebozo.html",
  },
  {
    name:"No-Sew Ring Sling",
    location:"front",
    baseModifier:-4,
    difficulty:"beginner",
    url:"http://www.slingrings.com/nosew.php",
  },
  {
    name:"Semi Front Wrap Cross Carry",
    location:"front",
    baseModifier:-3,
    difficulty:"intermediate",
    url:"http://www.babywearinghamptonroads.org/2014/05/carry-of-month-semi-front-wrap-cross.html",
  },
  {
    name:"Short Cross Carry with Sling Ring",
    location:"front",
    baseModifier:-3,
    difficulty:"intermediate",
    url:"http://slingsandthingsfsot.wordpress.com/2013/02/02/carry-of-the-week-short-cross-carry/",
  },
  {
    name:"Front Reinforced Torso Rebozo",
    location:"front",
    baseModifier:-3,
    difficulty:"intermediate",
    url:"",
  },
  {
    name:"Kangaroo Carry",
    location:"front",
    baseModifier:-2,
    difficulty:"advance",
    url:"http://www.babywearinghamptonroads.org/2014/08/carry-of-month-kangaroo-carry.html",
  },
  {
    name:"Short Front Wrap Cross Carry Tied at Shoulder",
    location:"front",
    baseModifier:-2,
    difficulty:"intermediate",
    url:"",
  },
  {
    name:"Front Wrap Cross Carry Tied Under Bum",
    location:"front",
    baseModifier:-2,
    difficulty:"intermediate",
    url:"http://bwiofpeoria.org/?p=3D1249",
  },
  {
    name:"Half Front Wrap Cross Carry",
    location:"front",
    baseModifier:-2,
    difficulty:"intermediate",
    url:"http://bwiofpeoria.org/?p=3D1249",
  },
  {
    name:"Short Cross Carry",
    location:"front",
    baseModifier:-2,
    difficulty:"intermediate",
    url:"http://www.wrapyourbaby.com/shortx.htm",
  },
  {
    name:"Front Torso Carry WIth Midlength Wrap",
    location:"front",
    baseModifier:-2,
    difficulty:"intermediate",
    url:"",
  },
  {
    name:"Front Wrap Cross Carry Torso Carry",
    location:"front",
    baseModifier:-1,
    difficulty:"advance",
    url:"http://www.babywearinghamptonroads.org/2013/09/carry-of-month-front-wrap-cross-carry.html",
  },
  {
    name:"Front Double Hammock",
    location:"front",
    baseModifier:0,
    difficulty:"advance",
    url:"http://ottawababywearinggroup.blogspot.com/2013/12/cotw-46-front-double-hammock.html",
  },
  {
    name:"Reinforced Kangaroo Carry",
    location:"front",
    baseModifier:0,
    difficulty:"advance",
    url:"http://www.babywearinghamptonroads.org/2014/08/carry-of-month-kangaroo-carry.html",
  },
  {
    name:"Front Wrap Cross Carry",
    location:"front",
    baseModifier:0,
    difficulty:"beginner",
    url:"http://www.babywearinghamptonroads.org/2013/02/carry-of-month-front-wrap-cross-carry.html",
  },
  {
    name:"Pocket Wrap Cross Carry",
    location:"front",
    baseModifier:0,
    difficulty:"beginner",
    url:"http://www.calinbleu.com/the-pocket-wrap-cross-carry/",
  },
  {
    name:"Front Cross Carry",
    location:"front",
    baseModifier:0,
    difficulty:"beginner",
    url:"http://somdbabywearers.weebly.com/blog/front-cross-carry-photo-tutorial",
  },
  {
    name:"Front Wrap Cross Carry Tied at Shoulder",
    location:"front",
    baseModifier:0,
    difficulty:"intermediate",
    url:"",
  },
  {
    name:"Simple Hip Carry",
    location:"hip",
    baseModifier:-5,
    difficulty:"beginner",
    url:"",
  },
  {
    name:"Rebozo",
    location:"hip",
    baseModifier:-4,
    difficulty:"beginner",
    url:"",
  },
  {
    name:"No-Sew Ring Sling",
    location:"hip",
    baseModifier:-4,
    difficulty:"beginner",
    url:"http://www.slingrings.com/nosew.php",
  },
  {
    name:"Hip Kangaroo",
    location:"hip",
    baseModifier:-3,
    difficulty:"advance",
    url:"",
  },
  {
    name:"Hip Reinforced Torso Carry",
    location:"hip",
    baseModifier:-3,
    difficulty:"intermediate",
    url:"",
  },
  {
    name:"Coolest Hip Cross Carry",
    location:"hip",
    baseModifier:-2,
    difficulty:"advance",
    url:"",
  },
  {
    name:"Coolest Hip Cross Carry with Reverse Passes",
    location:"hip",
    baseModifier:-2,
    difficulty:"advance",
    url:"",
  },
  {
    name:"Hip Cross Carry",
    location:"hip",
    baseModifier:-2,
    difficulty:"beginner",
    url:"http://www.wrapyourbaby.com/hipcrosscarry.html",
  },
  {
    name:"Robin’s Hip Carry",
    location:"hip",
    baseModifier:-2,
    difficulty:"beginner",
    url:"http://www.babywearinghamptonroads.org/2014/03/carry-of-month-robins-hip-carry.html",
  },
  {
    name:"Hip Cross Carry Pre-Tied",
    location:"hip",
    baseModifier:-2,
    difficulty:"intermediate",
    url:"",
  },
  {
    name:"Poppin’s Hip cary",
    location:"hip",
    baseModifier:-2,
    difficulty:"intermediate",
    url:"http://www.babywearinghamptonroads.org/2013/01/carry-of-month-poppins-hip-carry.html",
  },
  {
    name:"Reinforced Robin’s Hip Carry",
    location:"hip",
    baseModifier:0,
    difficulty:"beginner",
    url:"",
  },
  {
    name:"Hip Wrap Cross Carry Tied at Shoulder",
    location:"hip",
    baseModifier:0,
    difficulty:"intermediate",
    url:"",
  },
  {
    name:"Rucksack Tied Under Bum",
    location:"back",
    baseModifier:-4,
    difficulty:"intermediate",
    url:"http://canadianbabywearingschool.com/?p=3D276",
  },
  {
    name:"Rucksack Tied at Shoulder",
    location:"back",
    baseModifier:-4,
    difficulty:"intermediate",
    url:"",
  },
  {
    name:"Half Jordan’s Back Carry",
    location:"back",
    baseModifier:-4,
    difficulty:"intermediate",
    url:"http://ottawababywearinggroup.blogspot.com/2014/01/cotw-49-half-jordans-back-carry.html",
  },
  {
    name:"Half Jordan’s Back Carry without Shoulderflip",
    location:"back",
    baseModifier:-4,
    difficulty:"intermediate",
    url:"http://ottawababywearinggroup.blogspot.com/2014/01/cotw-49-half-jordans-back-carry.html",
  },
  {
    name:"Double Hammock Double Rings",
    location:"back",
    baseModifier:-4,
    difficulty:"intermediate",
    url:"",
  },
  {
    name:"Reinforced Rear Rebozo Rucksack",
    location:"back",
    baseModifier:-4,
    difficulty:"intermediate",
    url:"http://babywearingaroundtulsa.blogspot.com/2013/09/cotw-rrrr-reinforced-rear-ruck-rebozo.html",
  },
  {
    name:"Torso Carry",
    location:"back",
    baseModifier:-4,
    difficulty:"advance",
    url:"",
  },
  {
    name:"Rebozo Back Carry",
    location:"back",
    baseModifier:-4,
    difficulty:"intermediate",
    url:"",
  },
  {
    name:"Double Rebozo Shoulder to Shoulder Knotless",
    location:"back",
    baseModifier:-3,
    difficulty:"advance",
    url:"http://www.babywearinghamptonroads.org/2013/10/carry-of-month-double-rebozo-with.html",
  },
  {
    name:"Double Hammock Torso Carry",
    location:"back",
    baseModifier:-3,
    difficulty:"advance",
    url:"http://www.babywearinghamptonroads.org/2013/07/carry-of-month-double-hammock-torso.html",
  },
  {
    name:"Rucksack with a Candy Cane Chest Belt",
    location:"back",
    baseModifier:-3,
    difficulty:"intermediate",
    url:"",
  },
  {
    name:"Double Hammock Rebozo",
    location:"back",
    baseModifier:-3,
    difficulty:"intermediate",
    url:"http://www.babywearinghamptonroads.org/2013/08/carry-of-month-double-hammock-rebozo.html",
  },
  {
    name:"Double Rebozo",
    location:"back",
    baseModifier:-3,
    difficulty:"intermediate",
    url:"",
  },
  {
    name:"Short Back Cross Carry",
    location:"back",
    baseModifier:-3,
    difficulty:"intermediate",
    url:"http://ottawababywearinggroup.blogspot.com/2013/11/cotw-42-short-back-cross-carry.html",
  },
  {
    name:"Shepard’s Carry",
    location:"back",
    baseModifier:-3,
    difficulty:"intermediate",
    url:"http://phoenixbabywearers.blogspot.com/2014/05/carry-of-month-may-shepherds-carry.html",
  },
  {
    name:"Shepard’s Carry with Cross Passes",
    location:"back",
    baseModifier:-3,
    difficulty:"intermediate",
    url:"",
  },
  {
    name:"Rucksack",
    location:"back",
    baseModifier:-2,
    difficulty:"beginner",
    url:"http://www.babywearinghamptonroads.org/2013/04/carry-of-month-ruck.html",
  },
  {
    name:"Double Hammock Tied at Shoulder",
    location:"back",
    baseModifier:-2,
    difficulty:"intermediate",
    url:"http://suncitybabywearing.wordpress.com/2014/01/13/double-hammock-tied-at-shoulder-using-one-tail/",
  },
  {
    name:"Double Hammock Tied Under Bum",
    location:"back",
    baseModifier:-2,
    difficulty:"intermediate",
    url:"",
  },
  {
    name:"Poppin’s Back Carry (Coppins)",
    location:"back",
    baseModifier:-2,
    difficulty:"intermediate",
    url:"",
  },
  {
    name:"Double Rebozo Shoulder to Shoulder Tied Under Bum",
    location:"back",
    baseModifier:-1,
    difficulty:"advance",
    url:"http://www.babywearinghamptonroads.org/2013/10/carry-of-month-double-rebozo-with.html",
  },
  {
    name:"Back Wrap Cross Carry",
    location:"back",
    baseModifier:-1,
    difficulty:"beginner",
    url:"http://www.wrapyourbaby.com/backwrapcrosscarry.htm",
  },
  {
    name:"Back Wrap Cross Carry with Chest Belt",
    location:"back",
    baseModifier:-1,
    difficulty:"beginner",
    url:"http://www.babywearinghamptonroads.org/2012/12/back-wrap-cross-carry-BWCC.html",
  },
  {
    name:"Back Wrap Cross Carry with Ruck Straps",
    location:"back",
    baseModifier:-1,
    difficulty:"beginner",
    url:"",
  },
  {
    name:"Secure High Back Carry",
    location:"back",
    baseModifier:-1,
    difficulty:"beginner",
    url:"http://www.babywearinghamptonroads.org/2014/07/carry-of-month-secure-high-back-carry.html",
  },
  {
    name:"Reinforced Ruckscack",
    location:"back",
    baseModifier:-1,
    difficulty:"beginner",
    url:"https://babywearerscircle.wordpress.com/tag/reinforced-rucksack-carry/",
  },
  {
    name:"Rucksack Tied Tibetan",
    location:"back",
    baseModifier:-1,
    difficulty:"intermediate",
    url:"http://www.wrapyourbaby.com/rucksack.htm",
  },
  {
    name:"Rucksack with a Sternum Belt",
    location:"back",
    baseModifier:-1,
    difficulty:"intermediate",
    url:"",
  },
  {
    name:"Christina’s Ruckless Back Carry",
    location:"back",
    baseModifier:-1,
    difficulty:"intermediate",
    url:"http://www.babywearinghamptonroads.org/2014/02/carry-of-month-christinas-ruckless-back.html",
  },
  {
    name:"Double Hammock with a Candy Cane Chest Belt",
    location:"back",
    baseModifier:-1,
    difficulty:"intermediate",
    url:"http://suncitybabywearing.wordpress.com/2014/01/13/double-hammock-tied-at-shoulder-middle-marker-start/",
  },
  {
    name:"Norwegian Wiggle Proof",
    location:"back",
    baseModifier:-1,
    difficulty:"intermediate",
    url:"",
  },
  {
    name:"Back Wrap Cross Carry with a Sweetheart Neckliine",
    location:"back",
    baseModifier:0,
    difficulty:"advance",
    url:"http://slingingjoey.blogspot.com/2013/05/tutorial-back-wrap-cross-carry-with.html",
  },
  {
    name:"Double Hammock Salt Water Finish",
    location:"back",
    baseModifier:0,
    difficulty:"advance",
    url:"http://www.wrapyourbaby.com/doublehammockvariations.html",
  },
  {
    name:"Double Hammock Fresh Water Finish",
    location:"back",
    baseModifier:0,
    difficulty:"advance",
    url:"https://www.youtube.com/watch?v=c9KysQpAXsw",
  },
  {
    name:"Double Hammock Poppins Carry",
    location:"back",
    baseModifier:0,
    difficulty:"advance",
    url:"http://ottawababywearinggroup.blogspot.com/2013/06/cotw-22-poppins-double-hammock.html",
  },
  {
    name:"Double Hammock with Sternum Belt",
    location:"back",
    baseModifier:1,
    difficulty:"advance",
    url:"",
  },
  {
    name:"Giselle’s Back Carry",
    location:"back",
    baseModifier:0,
    difficulty:"intermediate",
    url:"",
  },
  {
    name:"Frankencarry",
    location:"back",
    baseModifier:1,
    difficulty:"advance",
    url:"",
  },
  {
    name:"Jordan’s Back Carry",
    location:"back",
    baseModifier:0,
    difficulty:"intermediate",
    url:"http://thecarryingworks.wordpress.com/2014/04/30/may-2014-jordans-back-carry/",
  },
  {
    name:"Jordan’s Back Carry Symmetrical",
    location:"back",
    baseModifier:-2,
    difficulty:"intermediate",
    url:"",
  },
  {
    name:"Elleville Jordan’s Back Carry",
    location:"back",
    baseModifier:0,
    difficulty:"intermediate",
    url:"http://wrapyourbaby.com/ellevilljbc.html",
  },
  {
    name:"Double Hammock",
    location:"back",
    baseModifier:0,
    difficulty:"intermediate",
    url:"http://www.babywearinghamptonroads.org/2013/06/carry-of-month-double-hammock-back-carry.html",
  },
  {
    name:"Mermaid Carry",
    location:"back",
    baseModifier:0,
    difficulty:"advance",
    url:"http://ottawababywearinggroup.blogspot.com/2013/07/cotw-23-mermaid-carry.html",
  },
  {
    name:"Wendy’s Double Hammock",
    location:"back",
    baseModifier:-1,
    difficulty:"intermediate",
    url:"http://thebabywearer.com/forum/threads/my-new-favorite-carry-dh-chunei-tied-at-the-shoulder-dubbed-wdh.366804/",
  },
  {
    name:"Double Rebozo Shoulder to Shoulder Tied in Front",
    location:"back",
    baseModifier:1,
    difficulty:"advance",
    url:"http://www.babywearinghamptonroads.org/2013/10/carry-of-month-double-rebozo-with.html",
  },
  {
    name:"Double Hammock Tied Tibetan",
    location:"back",
    baseModifier:1,
    difficulty:"advance",
    url:"",
  },
  {
    name:"Double Hammock Shoulder to Shoulder",
    location:"back",
    baseModifier:-1,
    difficulty:"advance",
    url:"",
  },
  {
    name:"Xena’s Double Hammock",
    location:"back",
    baseModifier:1,
    difficulty:"advance",
    url:"",
  },
  {
    name:"Wiggle Proof Back Carry",
    location:"back",
    baseModifier:1,
    difficulty:"advance",
    url:"http://thebabywearer.com/forum/threads/wiggle-proof-back-carry-photo-instructions.112898/",
  },
  {
    name:"Taiwanese Carry",
    location:"back",
    baseModifier:1,
    difficulty:"intermediate",
    url:"",
  }]